name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: pyspelling-requirements.txt

      - name: Install aspell
        run: sudo apt-get install aspell aspell-en aspell-fr

      - name: Install python dependencies
        run: pip install -r pyspelling-requirements.txt

      - name: Spellcheck
        run: python -m pyspelling
